/* @vitest-environment jsdom */
import { afterEach, describe, expect, it, vi } from "vitest";
import { downloadReportExportFile } from "./reportExportDownload";

const originalCreateObjectUrl = URL.createObjectURL;
const originalRevokeObjectUrl = URL.revokeObjectURL;

afterEach(() => {
  Object.defineProperty(URL, "createObjectURL", {
    configurable: true,
    value: originalCreateObjectUrl,
  });
  Object.defineProperty(URL, "revokeObjectURL", {
    configurable: true,
    value: originalRevokeObjectUrl,
  });
  vi.restoreAllMocks();
});

describe("report export download helper", () => {
  it("downloads the generated bytes and revokes the object URL", () => {
    const createObjectUrl = vi.fn(() => "blob:report-export");
    const revokeObjectUrl = vi.fn();
    const click = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    Object.defineProperty(URL, "createObjectURL", {
      configurable: true,
      value: createObjectUrl,
    });
    Object.defineProperty(URL, "revokeObjectURL", {
      configurable: true,
      value: revokeObjectUrl,
    });

    downloadReportExportFile({
      format: "csv",
      fileName: "fleet-report.csv",
      mimeType: "text/csv;charset=utf-8",
      text: "Vehicle",
      bytes: new Uint8Array([86, 101, 104, 105, 99, 108, 101]),
    });

    expect(createObjectUrl).toHaveBeenCalledWith(expect.any(Blob));
    expect(click).toHaveBeenCalledTimes(1);
    expect(document.querySelector("a[download='fleet-report.csv']")).toBeNull();
    expect(revokeObjectUrl).toHaveBeenCalledWith("blob:report-export");
  });
});
