import type {
  ReportDefinition,
  ReportOutputMode,
  ReportParameterDefinition,
} from "../models/reports";
import { TELTONIKA_TELEMETRY_SIGNAL_DEFINITIONS } from "../models/teltonikaCatalog";

const ALL_REPORT_OUTPUT_MODES: ReportOutputMode[] = ["preview", "print", "export", "email", "schedule"];

const REPORT_PARAMETER_IDS = new Set([
  "speed",
  "ignition",
  "movement",
  "fuelLevel",
  "fuelUsedGps",
  "fuelRateGps",
  "batteryLevel",
  "batteryVoltage",
  "externalVoltage",
  "engineRpm",
  "gnssStatus",
  "gnssHdop",
  "gsmSignal",
  "totalOdometer",
  "tripOdometer",
  "iButton",
  "alarm",
]);

export interface CreateReportDefinitionsOptions {
  demoDefaults?: boolean;
}

export function createReportParameters(): ReportParameterDefinition[] {
  return TELTONIKA_TELEMETRY_SIGNAL_DEFINITIONS
    .filter((signal) => REPORT_PARAMETER_IDS.has(signal.id))
    .map((signal) => ({
      ...signal,
      reportCategoryIds: (() => {
        if (signal.id === "alarm") return ["alarms", "safety"];
        if (signal.id.includes("fuel")) return ["fuel", "operations"];
        if (signal.id === "gnssHdop" || signal.id === "gnssStatus" || signal.id === "gsmSignal") {
          return ["diagnostics", "assets"];
        }
        if (signal.id === "batteryLevel" || signal.id === "batteryVoltage" || signal.id === "externalVoltage" || signal.id === "engineRpm") {
          return ["assets", "diagnostics"];
        }
        if (signal.id === "iButton") return ["driver"];
        if (signal.id === "totalOdometer" || signal.id === "tripOdometer") return ["trips", "operations"];
        return ["operations"];
      })() as ReportParameterDefinition["reportCategoryIds"],
    }));
}

export function createReportDefinitions(options: CreateReportDefinitionsOptions = {}): ReportDefinition[] {
  const demoDefaults = options.demoDefaults === true;
  const allVehicles = { mode: "all" as const };

  return [
    {
      id: "daily-summary",
      name: "Fleet Daily Summary",
      category: "operations",
      description: "Daily mileage, trips, alarms, and selected Teltonika telemetry.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["speed", "ignition", "movement", "fuelLevel", "totalOdometer", "tripOdometer", "alarm"],
      defaultParameterIds: ["speed", "ignition", "movement", "totalOdometer", "alarm"],
      requiredCapabilities: ["speed", "movement", "ignition"],
      optionalCapabilities: ["fuelLevel", "odometer", "alarms", "gnssHdop", "gsmSignal"],
      groupingOptions: ["vehicle", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["sum", "average", "count"],
      defaultAggregation: "sum",
      availableColumns: ["vehicle", "time", "speed", "ignition", "movement", "totalOdometer", "tripOdometer", "alarm"],
      defaultColumnIds: ["vehicle", "time", "speed", "movement", "tripOdometer", "alarm"],
      availableCharts: ["distance-by-day", "activity-by-vehicle", "alarm-severity"],
      defaultChartIds: ["distance-by-day", "activity-by-vehicle"],
      previewSections: ["summary", "charts", "table"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "today" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
    {
      id: "alarms",
      name: "Alarms And Events",
      category: "alarms",
      description: "Alarm events with vehicle and source attribute context.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["alarm", "speed", "ignition", "gsmSignal"],
      defaultParameterIds: ["alarm", "speed", "ignition", "gsmSignal"],
      requiredCapabilities: ["alarms"],
      optionalCapabilities: ["speed", "ignition", "gsmSignal"],
      groupingOptions: ["vehicle", "severity", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["count"],
      defaultAggregation: "count",
      availableColumns: ["vehicle", "time", "alarm", "speed", "ignition", "gsmSignal"],
      defaultColumnIds: ["vehicle", "time", "alarm", "speed", "gsmSignal"],
      availableCharts: ["severity-distribution", "alarm-timeline"],
      defaultChartIds: ["severity-distribution"],
      previewSections: ["summary", "timeline", "table"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "last7Days" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
    {
      id: "fuel-management",
      name: "Fuel Management",
      category: "fuel",
      description: "Fuel level, consumption, distance, and odometer changes.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["fuelLevel", "fuelUsedGps", "fuelRateGps", "totalOdometer", "tripOdometer", "speed"],
      defaultParameterIds: ["fuelLevel", "fuelRateGps", "tripOdometer", "speed"],
      requiredCapabilities: ["fuelLevel"],
      optionalCapabilities: ["fuelConsumed", "odometer", "speed"],
      groupingOptions: ["vehicle", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["average", "min", "max", "sum"],
      defaultAggregation: "average",
      availableColumns: ["vehicle", "time", "fuelLevel", "fuelUsedGps", "fuelRateGps", "tripOdometer", "totalOdometer", "speed"],
      defaultColumnIds: ["vehicle", "time", "fuelLevel", "fuelRateGps", "tripOdometer"],
      availableCharts: ["fuel-level-history", "fuel-rate-by-vehicle"],
      defaultChartIds: ["fuel-level-history"],
      previewSections: ["summary", "charts", "table"],
      vehicleSelection: demoDefaults ? { mode: "selected", vehicleIds: ["veh-atlas-12", "veh-courier-19"] } : allVehicles,
      period: { type: "preset", preset: "last7Days" },
      timeWindow: { preset: "businessHours", startTime: "08:00", endTime: "18:00" },
      schedule: demoDefaults
        ? { enabled: true, frequency: "weekly", recipientEmails: ["fleet.ops@example.com"] }
        : { enabled: false, frequency: "weekly" },
    },
    {
      id: "asset-health",
      name: "GNSS / Tracker Health",
      category: "diagnostics",
      description: "Tracker power, GSM, GNSS, and engine telemetry for asset checks.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["batteryLevel", "batteryVoltage", "externalVoltage", "gsmSignal", "gnssStatus", "gnssHdop", "engineRpm"],
      defaultParameterIds: ["batteryLevel", "externalVoltage", "gsmSignal", "gnssHdop"],
      requiredCapabilities: ["gnssHdop", "gsmSignal"],
      optionalCapabilities: ["batteryVoltage", "externalVoltage", "rpm"],
      groupingOptions: ["vehicle", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["average", "min", "max"],
      defaultAggregation: "average",
      availableColumns: ["vehicle", "time", "batteryLevel", "batteryVoltage", "externalVoltage", "gsmSignal", "gnssStatus", "gnssHdop", "engineRpm"],
      defaultColumnIds: ["vehicle", "time", "batteryLevel", "externalVoltage", "gsmSignal", "gnssHdop"],
      availableCharts: ["signal-quality", "voltage-trend", "gnss-hdop"],
      defaultChartIds: ["signal-quality", "gnss-hdop"],
      previewSections: ["summary", "charts", "table"],
      vehicleSelection: demoDefaults ? { mode: "status", statusIds: ["moving", "idling", "alerting"] } : allVehicles,
      period: { type: "preset", preset: "today" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
    {
      id: "trip-activity",
      name: "Vehicle Trips",
      category: "trips",
      description: "Movement, ignition, speed, and odometer context for route activity.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["movement", "ignition", "speed", "tripOdometer", "totalOdometer"],
      defaultParameterIds: ["movement", "ignition", "speed", "tripOdometer"],
      requiredCapabilities: ["movement", "ignition", "speed", "tripHistory"],
      optionalCapabilities: ["odometer", "driverIdentification", "alarms"],
      groupingOptions: ["vehicle", "day", "driver"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["sum", "average", "max", "count"],
      defaultAggregation: "sum",
      availableColumns: ["vehicle", "time", "movement", "ignition", "speed", "tripOdometer", "totalOdometer"],
      defaultColumnIds: ["vehicle", "time", "movement", "ignition", "speed", "tripOdometer"],
      availableCharts: ["distance-by-day", "speed-profile", "trip-count"],
      defaultChartIds: ["distance-by-day", "speed-profile"],
      previewSections: ["summary", "charts", "table", "map"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "last7Days" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false, frequency: "daily" },
    },
    {
      id: "vehicle-stops",
      name: "Vehicle Stops / Idling",
      category: "operations",
      description: "Stops, ignition-on stationary time, and idling-heavy periods.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["movement", "ignition", "speed", "tripOdometer"],
      defaultParameterIds: ["movement", "ignition", "speed"],
      requiredCapabilities: ["movement", "ignition", "speed"],
      optionalCapabilities: ["tripHistory", "odometer"],
      groupingOptions: ["vehicle", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["sum", "count", "average"],
      defaultAggregation: "count",
      availableColumns: ["vehicle", "time", "movement", "ignition", "speed", "tripOdometer"],
      defaultColumnIds: ["vehicle", "time", "movement", "ignition", "speed"],
      availableCharts: ["idle-time-by-vehicle", "stops-by-day"],
      defaultChartIds: ["idle-time-by-vehicle"],
      previewSections: ["summary", "charts", "table"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "last7Days" },
      timeWindow: { preset: "businessHours", startTime: "08:00", endTime: "18:00" },
      schedule: { enabled: false },
    },
    {
      id: "telemetry-history",
      name: "Signal / Telemetry History",
      category: "diagnostics",
      description: "Selected tracker signals over time with min, max, average, and raw datapoints.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["speed", "fuelLevel", "batteryLevel", "externalVoltage", "engineRpm", "gnssHdop", "gsmSignal"],
      defaultParameterIds: ["speed", "fuelLevel", "batteryLevel", "gnssHdop"],
      requiredCapabilities: ["speed"],
      optionalCapabilities: ["fuelLevel", "batteryVoltage", "externalVoltage", "rpm", "gnssHdop", "gsmSignal"],
      groupingOptions: ["vehicle", "signal", "day"],
      defaultGrouping: "signal",
      aggregationOptions: ["average", "min", "max"],
      defaultAggregation: "average",
      availableColumns: ["vehicle", "time", "speed", "fuelLevel", "batteryLevel", "externalVoltage", "engineRpm", "gnssHdop", "gsmSignal"],
      defaultColumnIds: ["vehicle", "time", "speed", "fuelLevel", "batteryLevel", "gnssHdop"],
      availableCharts: ["signal-history", "min-max-band"],
      defaultChartIds: ["signal-history"],
      previewSections: ["summary", "charts", "table", "raw"],
      vehicleSelection: demoDefaults ? { mode: "selected", vehicleIds: ["veh-atlas-12"] } : allVehicles,
      period: { type: "preset", preset: "today" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
    {
      id: "driver-activity",
      name: "iButton Activity",
      category: "driver",
      description: "Driver identifier activity, trips, ignition, and movement context.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["pdf", "xlsx", "csv", "json"],
      defaultOutputMode: "preview",
      parameterIds: ["iButton", "movement", "ignition", "speed", "alarm"],
      defaultParameterIds: ["iButton", "movement", "ignition", "speed"],
      requiredCapabilities: ["driverIdentification"],
      optionalCapabilities: ["movement", "ignition", "speed", "alarms"],
      groupingOptions: ["driver", "vehicle", "day"],
      defaultGrouping: "driver",
      aggregationOptions: ["count", "sum", "average"],
      defaultAggregation: "count",
      availableColumns: ["vehicle", "time", "iButton", "movement", "ignition", "speed", "alarm"],
      defaultColumnIds: ["vehicle", "time", "iButton", "movement", "ignition", "speed"],
      availableCharts: ["driver-activity", "driver-trip-count"],
      defaultChartIds: ["driver-activity"],
      previewSections: ["summary", "charts", "table"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "last7Days" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
    {
      id: "canbus-details",
      name: "CANBus Details",
      category: "diagnostics",
      description: "Future CANBus report. Disabled until selected vehicles expose CANBus attributes.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["xlsx", "json"],
      defaultOutputMode: "preview",
      parameterIds: [],
      defaultParameterIds: [],
      requiredCapabilities: ["canBus"],
      groupingOptions: ["vehicle", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["average", "min", "max"],
      defaultAggregation: "average",
      availableColumns: ["vehicle", "time"],
      defaultColumnIds: ["vehicle", "time"],
      availableCharts: [],
      defaultChartIds: [],
      previewSections: ["summary", "table"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "today" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
    {
      id: "temperature",
      name: "Temperature",
      category: "diagnostics",
      description: "Future temperature report. Disabled until temperature attributes are mapped.",
      supportedOutputModes: [...ALL_REPORT_OUTPUT_MODES],
      supportedExportFormats: ["xlsx", "json"],
      defaultOutputMode: "preview",
      parameterIds: [],
      defaultParameterIds: [],
      requiredCapabilities: ["temperature"],
      groupingOptions: ["vehicle", "day"],
      defaultGrouping: "vehicle",
      aggregationOptions: ["average", "min", "max"],
      defaultAggregation: "average",
      availableColumns: ["vehicle", "time"],
      defaultColumnIds: ["vehicle", "time"],
      availableCharts: [],
      defaultChartIds: [],
      previewSections: ["summary", "table"],
      vehicleSelection: allVehicles,
      period: { type: "preset", preset: "today" },
      timeWindow: { preset: "fullDay" },
      schedule: { enabled: false },
    },
  ];
}
